---

- name: Install bin files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/bin/"
    owner: "root"
    group: "root"
    mode: 0755
  with_fileglob:
    - "files/bin/*"

- name: Install bin files by templates
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/usr/bin/{{ item[:-3] | basename }}"
    owner: "root"
    group: "root"
    mode: 0755
  with_fileglob:
    - "templates/bin/*"


