---

- name: Add gpg dependency for key handling
  ansible.builtin.apt:
    name: "gpg"

- name: Add repo key
  ansible.builtin.get_url:
    url: "https://repos.influxdata.com/influxdata-archive.key"
    dest: "/usr/share/keyrings/influxdata-archive.gpg"
    mode: "0644"
    owner: "root"
    group: "root"
  when: "not ansible_check_mode"

- name: Add influx repo
  register: "influxrepositoryadded"
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/influxdata-archive.gpg] https://repos.influxdata.com/debian stable main"
    filename: "influxdata"

- name: Update apt chache to get influxdb packages
  ansible.builtin.apt:
    update_cache: true
  when: "influxrepositoryadded is changed"

- name: Install influxdb2 from repo
  register: "influxinstall"
  ansible.builtin.apt:
    name: influxdb2

- name: Generate config file
  notify: "Reload influxdb"
  ansible.builtin.template:
    src: "influx2.config.toml.j2"
    dest: "/etc/influxdb/config.toml"

- name: Ensure engine directory exists and has correct ownership
  ansible.builtin.file:
    state: "directory"
    path: "{{ influx2_engine_path }}"
    owner: "influxdb"
    group: "influxdb"
    recurse: true

- name: Enable service
  ansible.builtin.systemd_service:
    name: "influxdb"
    enabled: true
    state: "started"

- name: Firewall
  include_tasks: "firewall.yml"
