---

- name: Install dependencies
  ansible.builtin.apt:
    pkg:
    - "git"
    - "rsync"

- name: Ensure ansible dir
  ansible.builtin.file:
      dest: "/var/lib/ansible"
      state: "directory"

- name: Check installed go version
  register: "goversion"
  ansible.builtin.copy:
    content: "{{ go_version }}"
    dest: "/var/lib/ansible/go_version"

- name: Download and install go
  ansible.builtin.unarchive:
    src: "https://storage.googleapis.com/golang/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "/usr/local"
    remote_src: true
  when: "goversion is changed"

- name: Install path to go stuff
  ansible.builtin.template:
    src: "go.sh.j2"
    dest: "/etc/profile.d/go.sh"
    mode: "0755"

- name: Check if yanic is already installed
  register: "yanic_source_dir"
  ansible.builtin.stat:
    path: "{{ yanic_source_path }}"

- name: Install yanic if not yet installed
  register: "fresh_install"
  ansible.builtin.command: "{{ go_bin_path }}/go install yanic"
  when: "not yanic_source_dir.stat.exists"

- name: Create patch directory
  ansible.builtin.file:
    path: "{{ yanic_source_path }}/patches"
    state: "directory"

- name: Transfer local patches
  register: "patch_sync"
  ansible.posix.synchronize:
    src: "files/patches/"
    dest: "{{ yanic_source_path }}/patches"
    archive: false
    checksum: true
    recursive: true
    delete: true

- name: Check if target commit exists in git tree
  register: "commit_search"
  ansible.builtin.command:
    chdir: "{{ yanic_source_path }}"
    cmd: "git cat-file -e {{ yanic_commit }}^{commit}"
  changed_when: "commit_search.rc!=0"
  check_mode: false
  failed_when: "commit_search.rc != 0 and commit_search.rc != 128"

- name: Update yanic to "{{ yanic_commit }}"
  register: "yanic_repo"
  ansible.builtin.git:
    repo: "https://{{ yanic_repo_path }}.git"
    dest: "{{ yanic_source_path }}"
    update: true
    force: true
    version: "{{ yanic_commit }}"
  when: "fresh_install.changed or commit_search.rc==128 or patch_sync.changed"

- name: Apply patches
  register: "patches"
  ansible.builtin.script:
    cmd: "files/apply_patches.sh"
    chdir: "{{ yanic_source_path }}"
  when: "patch_sync.changed or yanic_repo.changed"

- name: Get all project dependencies
  ansible.builtin.command:
    chdir: "{{ yanic_source_path }}"
    cmd: "{{ go_bin_path }}/go get ."
  when: "patch_sync.changed or yanic_repo.changed"

- name: Build yanic with applied patches
  ansible.builtin.command:
    chdir: "{{ yanic_source_path }}"
    cmd: "{{ go_bin_path }}/go build ."
  environment:
    GOPATH: "{{ go_path }}"
  when: "patches.changed"

- name: Install built yanic
  notify: "Restart yanic"
  ansible.builtin.command:
    chdir: "{{ yanic_source_path }}"
    cmd: "{{ go_bin_path }}/go install ."
  environment:
    GOPATH: "{{ go_path }}"
  when: "patches.changed"

- name: Create yanic user
  ansible.builtin.user:
    name: "{{ yanic_user }}"
    group: "{{ yanic_group }}"
    system: true

- name: Ensure persist directory, if needed
  ansible.builtin.file:
    path: "/var/lib/yanic/"
    state: "directory"
    owner: "yanic"
  when: "yanic_nodes_enabled"

- name: Ensure nodes path, if needed
  ansible.builtin.file:
    path: "{{ yanic_nodes_path }}"
    state: "directory"
    owner: "www-data"
  when: "yanic_nodes_enabled"

- name: Configure yanic (DIFF REDACTED)
  notify: "Restart yanic"
  ansible.builtin.template:
    src: "config.yml.j2"
    dest: "/etc/yanic.conf"
  diff: "{{ show_secret_diffs }}"

- name: Copy systemd service
  notify: "Daemon reload"
  ansible.builtin.template:
    src: "yanic.service.j2"
    dest: "/lib/systemd/system/yanic.service"

- name: Generate firewall config stanza (ferm)
  register: "ferm_changed"
  notify: "reload ferm"
  ansible.builtin.template:
    src: "ferm.conf.j2"
    dest: "/etc/ferm/conf.d/50-yanic.conf"

- name: Enable yanic
  ansible.builtin.systemd_service:
    name: "yanic"
    state: "started"
    enabled: true

- name: sysctl parameters for neigh gc_thresh
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: "/etc/sysctl.d/50-gc_thresh.conf"
    reload: true
  loop: [
    { name: 'net.ipv6.neigh.default.gc_thresh1', value: '32768' },
    { name: 'net.ipv6.neigh.default.gc_thresh2', value: '65536' },
    { name: 'net.ipv6.neigh.default.gc_thresh3', value: '131072' }
  ]

- name: Run Graveyard tasks
  include_tasks: "graveyard.yml"
