---

web_osm_fqdn: "tiles.ffh.zone"
web_osm_carto_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32313235336365316634323462356665343837623165623830313535386363643366613930636136
          3864363936366337383232343338626166306134356634330a393732646135653135323339393730
          65386131333166353939623066613636356333353234393965643365383838383561313764363831
          3130623663663030620a646534373631643131616233633165386165376536613465656137373965
          36303935356262356664653961393262653362633463353339316264363765663264353537653834
          3638363633396431306331363233636461376463626261336135

nginx_sites:
- domain: firmware.ffh.zone
  tls: true
  locations:
    - location: /
      type: proxy
      proxy_forward_url: http://127.0.0.1:8084/
      proxy_buffering: false
      proxy_pass_host: true
- domain: gluon-node-sense.ffh.zone
  tls: true
  locations:
    - location: /
      type: proxy
      proxy_forward_url: http://127.0.0.1:8085/
      proxy_buffering: false
      proxy_pass_host: true
- domain: raw-firmware.ffh.zone
  root: /var/www/domains/raw-firmware.ffh.zone
  tls: true
  locations:
    - location: /
      directory_index: true
- domain: ffh.zone
  root: /var/www/domains/ffh.zone/
  tls: true
  tls_redirect_to_https: true
  locations:
    - location: = /
      rewrite_params: '^ https://hannover.freifunk.net/wiki/Freifunk/Impressum'
- domain: www.ffh.zone
  root: /var/www/domains/ffh.zone/
  tls: true
  tls_redirect_to_https: true
  locations:
    - location: = /
      rewrite_params: '^ https://hannover.freifunk.net/wiki/Freifunk/Impressum'
- domain: hannover.freifunk.net
  root: /var/www/domains/hannover.freifunk.net/
  tls: true
  tls_redirect_to_https: true
  php: true
  locations:
    - location: = /
      type: proxy
      proxy_forward_url: http://127.0.0.1:4444
    - location: ~ (/video.html|/style.css|/img/.+)
      type: proxy
      proxy_forward_url: http://127.0.0.1:4444
    - location: = /api
      rewrite_params: '^ /api/ permanent'
    - location: /api/
      expires: -1
      alias: /var/www/apps/api/
    - location: = /download.html
      rewrite_params: '^ /download/ redirect'
    - location: = /download
      rewrite_params: '^ /download/ permanent'
    - location: = /images/
      rewrite_params: '^ /files/Router-Firmware/ redirect'
    - location: /files/
      directory_index: true
      disable_symlinks: true
      alias: /var/www/apps/files/
    - location: = /gluon-firmware-wizard
      rewrite_params: '^ /download/ redirect'
    - location: /download/
      alias: /var/www/apps/gluon-firmware-selector/
    - location: = /blog
      rewrite_params: '^ /blog/ permanent'
    - location: /blog/
      alias: /var/www/apps/blog/public/
    - location: /karte/config.json
      alias: /var/www/apps/meshviewer_configs/karte.json
    - location: /friedhof/config.json
      alias: /var/www/apps/meshviewer_configs/friedhof.json
    - location: = /karte
      rewrite_params: '^ /karte/ permanent'
    - location: /karte/
      alias: /var/www/apps/meshviewer/
    - location: = /friedhof
      rewrite_params: '^ /friedhof/ permanent'
    - location: /friedhof/
      alias: /var/www/apps/meshviewer/
    - location: = /device-pictures
      rewrite_params: '^ /device-pictures/ permanent'
    - location: /device-pictures/
      alias: /var/www/apps/device-pictures/pictures-svg/
    - location: = /sshauto
      rewrite_params: '^ /sshauto/ permanent'
    - location: /sshauto/
      alias: /var/www/apps/sshauto/

  custom_config: |
          #
          # General
          #
          location ~ (^/Fl(ue|ü)chtlings(wohn)?heime) {
            rewrite .* /wiki/Maschinenraum/Fluechtlingsheime;
          }

          rewrite ^/api/((graph|nodes|summary)\.json)$ https://harvester.ffh.zone/api/$1 permanent;

          #
          # Wiki related
          #
          set $foswiki_root "/var/www/apps/wiki";
          client_max_body_size 10M;   # Set to maximum attachment size, See also ATTACHFILESIZELIMIT
          location = /wiki/ {
            root $foswiki_root;
            rewrite .* /wiki/Main/WebHome;
          }
          location ~ ^/wiki/pub/(.*) {
            alias $foswiki_root/pub/$1;
            allow all;
          }
          location ~ ^/wiki/bin/ {
            root $foswiki_root;
            gzip off;
            fastcgi_pass             127.0.0.1:9000;
            fastcgi_split_path_info  ^(/wiki/bin/\w+)(.*);
            fastcgi_param            SCRIPT_FILENAME $foswiki_root/bin/$fastcgi_script_name;
            fastcgi_param            SCRIPT_NAME     $fastcgi_script_name;
            fastcgi_param            PATH_INFO       $fastcgi_path_info;
            include fastcgi_params;
          }
          location ~ (^/wiki/lib|^/wiki/data|^/wiki/locale|^/wiki/templates|^/wiki/tools|^/wiki/working) {
            root $foswiki_root;
            deny all;
          }
          if ($http_user_agent ~ ^SiteSucker|^iGetter|^larbin|^LeechGet|^RealDownload|^Teleport|^Webwhacker|^WebDevil|^Webzip|^Attache|^SiteSnagger|^WX_mail|^EmailCollector|^WhoWhere|^Roverbot|^ActiveAgent|^EmailSiphon|^CrownPeak-HttpAgent|^$) {
            rewrite .* /404.html break;
          }
          location ~ ^/wiki/(.*)$ {
            root $foswiki_root;
            rewrite ^/wiki/(.*)$ /wiki/bin/view/$1;
          }
- domain: tiles.ffh.zone
  root: /var/www/domains/tiles.ffh.zone/www
  tls: true
  tls_redirect_to_https: true
  untouchable: true
