---
# tasks file for ffh.docker

- name: Install dependencies
  ansible.builtin.apt:
    pkg:
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "gnupg"

- name: Prepare key directory for older Debian versions
  ansible.builtin.file:
    path: "/etc/apt/keyrings"
    state: "directory"
    mode: "0755"
    owner: "root"
    group: "root"
  when: "ansible_facts['distribution_version']|int < 12"

- name: Add Docker repo key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/debian/gpg"
    dest: "/etc/apt/keyrings/docker.key"
    mode: "0644"
    owner: "root"
    group: "root"
  when: "not ansible_check_mode"

- name: Add Docker repo
  register: dockerrepositoryadded
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.key] https://download.docker.com/linux/debian {{ ansible_facts['distribution_release'] }} stable"
    filename: "docker"

- name: Update apt chache to get Docker packages
  ansible.builtin.apt: update_cache=yes
  when: dockerrepositoryadded is changed

- name: Install Docker from repo
  register: dockerinstall
  ansible.builtin.apt:
    pkg:
    - "docker-ce"
    - "docker-ce-cli"
    - "containerd.io"

- name: Install daemon.json
  ansible.builtin.template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"
  notify: Restart Docker

- name: nftables stuff
  include_tasks: "nftables.yml"
  when: nftables_enabled is defined and nftables_enabled
