---

- name: Override nftables.service ExecStop behaviour, create directory
  ansible.builtin.file:
    path: "/etc/systemd/system/nftables.service.d/"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Override nftables.service ExecStop behaviour, drop config
  ansible.builtin.template:
    src: "nftables.service.conf.j2"
    dest: "/etc/systemd/system/nftables.service.d/50-no-execstop.conf"

- name: sysctl parameters for ip forwarding
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: "/etc/sysctl.d/99-docker.conf"
    reload: true
  loop: [
    { name: "net.ipv4.ip_forward", value: "1" },
    { name: "net.ipv6.conf.all.forwarding", value: "1" }
  ]

- name: Create nftables directory if necessary
  ansible.builtin.file:
    path: "/etc/nftables"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Allow forwarding for docker bridges
  notify: "reload nftables"
  ansible.builtin.template:
    src: "nftables.conf.j2"
    dest: "/etc/nftables/10-docker.conf"
    owner: "root"
    group: "root"
    mode: "0755"

