---

- name: Install dependencies (git, sudo)
  ansible.builtin.apt:
    update_cache: true
    pkg:
    - "git"
    - "sudo"

- name: Create auto user
  register: "createuser"
  ansible.builtin.user:
    name: "auto"
    system: true
    generate_ssh_key: true

# Manually deploy ssh pubkey to git server.

- name: Install autoupdate script
  ansible.builtin.template:
    src: "autoupdate.sh.j2"
    dest: "/home/auto/autoupdate.sh"
    owner: "auto"
    group: "auto"
    mode: "u=rwx,g=r,o=r"
