---

- name: Daemon reload
  notify: Restart yanic
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart yanic
  ansible.builtin.systemd_service:
    name: "yanic"
    state: "restarted"
