---

- name: Create working directory
  ansible.builtin.file:
    path: /opt/firmware-proxy/
    state: directory
    group: www-data

- name: Place servicefile
  notify: Daemon reload
  template:
    src: firmware-proxy.service.j2
    dest: /etc/systemd/system/firmware-proxy.service

- name: Enable firmware-proxy
  systemd:
    name: firmware-proxy
    state: started
    enabled: yes
