---

- name: Compile admin_authorized list
  ansible.builtin.set_fact:
    admin_authorized_merged: "{{ admin_authorized + admin_authorized_local }}"

- name: Compile admin_authorized_keys list
  ansible.builtin.set_fact:
    admin_authorized_keys: "{{ admin_pubkeys | selectattr('name', 'in', admin_authorized_merged) | map(attribute='key') | join('\n') }}"

- name: Install ssh keys
  ansible.posix.authorized_key:
    user: "root"
    state: "present"
    exclusive: true
    key: "{{ admin_authorized_keys }}"
  when: "'proxmoxes' not in group_names"

- name: Install host ca key in /etc/ssh/ssh_known_hosts
  notify: "Restart sshd"
  ansible.builtin.lineinfile:
    path: "/etc/ssh/ssh_known_hosts"
    regexp: "^@cert-authority \\*\\.ffh\\.zone ssh-"
    line: "@cert-authority *.ffh.zone {{ admin_host_ca_sshkey }}"

- name: Check if signed host certificate exists
  ansible.builtin.stat:
    path: "{{ remote_host_cert }}"
  register: "certfile"

- name: Create and sign ssh hostkey
  include_tasks: "hostkey.yml"
  when: "(certfile.stat.exists is defined and not certfile.stat.exists and not ansible_check_mode) or 'cert_renew' in ansible_run_tags"

- name: sysctl - Reboot on kernel panic
  ansible.posix.sysctl:
    sysctl_file: /etc/sysctl.d/50-panic.conf
    name: kernel.panic
    value: "10"
    state: present
    reload: yes
  when: reboot_on_kernelpanic == true and ansible_facts['virtualization_type'] != "lxc"

- name: Set timezone
  community.general.timezone:
    name: "Europe/Berlin"
