---

- name: Install nginx, php and getssl
  include_tasks: "install.yml"

- name: Configure nginx
  include_tasks: "config.yml"

- name: Configure sites
  include_tasks: "sites.yml"

- name: Firewalling
  include_tasks: "firewall.yml"
