---

- name: Allow other users to read /etc/wireguard
  ansible.builtin.file:
    path: "/etc/wireguard"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rx,o=rx"

- name: Create the peers directory
  ansible.builtin.file:
    path: "/etc/wireguard/peers"
    state: "directory"
    owner: "auto"
    group: "root"
    mode: "u=rwx,g=rx,o=rx"

- name: Clone the peers git
  become: true
  become_user: "auto"
  ansible.builtin.git:
    repo: "{{ mesh_wireguard_peers }}"
    dest: "/etc/wireguard/peers"
    accept_hostkey: true

- name: Install autoupdate peer script
  ansible.builtin.template:
    src: "autoupdate_wg.py.j2"
    dest: "/home/auto/autoupdate_wg.py"
    owner: "auto"
    group: "auto"
    mode: "u=rwx,g=r,o=r"

- name: Allow reloading the wireguard instance for user auto
  ansible.builtin.template:
    src: "user-auto-reload-wireguard"
    dest: "/etc/sudoers.d/user-auto-reload-wireguard"
    owner: "root"
    group: "root"
    mode: "0644"

- name: Set git config regarding pull strategy for auto user
  community.general.git_config:
    name: "pull.ff"
    value: "only"
    scope: "system"
    repo: "/etc/wireguard/peers"

- name: Install crontab for autoupdate
  ansible.builtin.cron:
    name: "autoupdate wireguard peers from git"
    user: "auto"
    minute: "*/1"
    job: >
      sudo /home/auto/autoupdate_wg.py
